[package]
name = "paperdash-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
rand = "0.8.5"
rocket = "0.5.0-rc.2"
image = "0.24.6"
webscreenshot = "0.2.2"
